<?php

use Illuminate\Database\Seeder;

class CarroModeloSeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('modelo')->insert([
            ['fk_montadora' => '1', 'descricao' => 'LEGEND'],
            ['fk_montadora' => '2', 'descricao' => 'FURGOVAN'],
            ['fk_montadora' => '2', 'descricao' => 'MARRUÁ'],
            ['fk_montadora' => '3', 'descricao' => '145'],
            ['fk_montadora' => '3', 'descricao' => '147'],
            ['fk_montadora' => '3', 'descricao' => '155'],
            ['fk_montadora' => '3', 'descricao' => '156'],
            ['fk_montadora' => '3', 'descricao' => '164'],
            ['fk_montadora' => '3', 'descricao' => '166'],
            ['fk_montadora' => '3', 'descricao' => '2300 Ti'],
            ['fk_montadora' => '3', 'descricao' => '4C'],
            ['fk_montadora' => '3', 'descricao' => 'SPIDER'],
            ['fk_montadora' => '4', 'descricao' => 'CLASSIC 427'],
            ['fk_montadora' => '4', 'descricao' => 'CLASSIC XK120'],
            ['fk_montadora' => '5', 'descricao' => 'HI-TOPIC'],
            ['fk_montadora' => '5', 'descricao' => 'ROCSTA'],
            ['fk_montadora' => '5', 'descricao' => 'TOPIC'],
            ['fk_montadora' => '5', 'descricao' => 'TOWNER'],
            ['fk_montadora' => '6', 'descricao' => 'DB7'],
            ['fk_montadora' => '6', 'descricao' => 'DB9'],
            ['fk_montadora' => '6', 'descricao' => 'DBS'],
            ['fk_montadora' => '6', 'descricao' => 'RAPIDE'],
            ['fk_montadora' => '6', 'descricao' => 'V12 VANTAGE'],
            ['fk_montadora' => '6', 'descricao' => 'VANQUISH'],
            ['fk_montadora' => '6', 'descricao' => 'VANTAGE'],
            ['fk_montadora' => '6', 'descricao' => 'VIRAGE'],
            ['fk_montadora' => '7', 'descricao' => '80'],
            ['fk_montadora' => '7', 'descricao' => 'A1'],
            ['fk_montadora' => '7', 'descricao' => 'A2'],
            ['fk_montadora' => '7', 'descricao' => 'A3'],
            ['fk_montadora' => '7', 'descricao' => 'A4'],
            ['fk_montadora' => '7', 'descricao' => 'A5'],
            ['fk_montadora' => '7', 'descricao' => 'A6'],
            ['fk_montadora' => '7', 'descricao' => 'A7'],
            ['fk_montadora' => '7', 'descricao' => 'A8'],
            ['fk_montadora' => '7', 'descricao' => 'ALLROAD'],
            ['fk_montadora' => '7', 'descricao' => 'Q3'],
            ['fk_montadora' => '7', 'descricao' => 'Q5'],
            ['fk_montadora' => '7', 'descricao' => 'Q7'],
            ['fk_montadora' => '7', 'descricao' => 'R8'],
            ['fk_montadora' => '7', 'descricao' => 'RS Q3'],
            ['fk_montadora' => '7', 'descricao' => 'RS2'],
            ['fk_montadora' => '7', 'descricao' => 'RS3'],
            ['fk_montadora' => '7', 'descricao' => 'RS4'],
            ['fk_montadora' => '7', 'descricao' => 'RS5'],
            ['fk_montadora' => '7', 'descricao' => 'RS6'],
            ['fk_montadora' => '7', 'descricao' => 'RS7'],
            ['fk_montadora' => '7', 'descricao' => 'S3'],
            ['fk_montadora' => '7', 'descricao' => 'S4'],
            ['fk_montadora' => '7', 'descricao' => 'S5'],
            ['fk_montadora' => '7', 'descricao' => 'S6'],
            ['fk_montadora' => '7', 'descricao' => 'S7'],
            ['fk_montadora' => '7', 'descricao' => 'S8'],
            ['fk_montadora' => '7', 'descricao' => 'SQ5'],
            ['fk_montadora' => '7', 'descricao' => 'TT'],
            ['fk_montadora' => '7', 'descricao' => 'TT RS'],
            ['fk_montadora' => '7', 'descricao' => 'TTS'],
            ['fk_montadora' => '8', 'descricao' => '3000'],
            ['fk_montadora' => '9', 'descricao' => 'TF'],
            ['fk_montadora' => '10', 'descricao' => 'BUGGY'],
            ['fk_montadora' => '11', 'descricao' => 'BROOKLANDS'],
            ['fk_montadora' => '11', 'descricao' => 'CONTINENTAL'],
            ['fk_montadora' => '12', 'descricao' => '1 M'],
            ['fk_montadora' => '12', 'descricao' => '116i'],
            ['fk_montadora' => '12', 'descricao' => '118i'],
            ['fk_montadora' => '12', 'descricao' => '120i'],
            ['fk_montadora' => '12', 'descricao' => '125i'],
            ['fk_montadora' => '12', 'descricao' => '130i'],
            ['fk_montadora' => '12', 'descricao' => '135i'],
            ['fk_montadora' => '12', 'descricao' => '220i'],
            ['fk_montadora' => '12', 'descricao' => '225i'],
            ['fk_montadora' => '12', 'descricao' => '316i'],
            ['fk_montadora' => '12', 'descricao' => '318i'],
            ['fk_montadora' => '12', 'descricao' => '318Ti'],
            ['fk_montadora' => '12', 'descricao' => '320i'],
            ['fk_montadora' => '12', 'descricao' => '323Ci'],
            ['fk_montadora' => '12', 'descricao' => '323i'],
            ['fk_montadora' => '12', 'descricao' => '323Ti'],
            ['fk_montadora' => '12', 'descricao' => '325Ci'],
            ['fk_montadora' => '12', 'descricao' => '325i'],
            ['fk_montadora' => '12', 'descricao' => '325iS'],
            ['fk_montadora' => '12', 'descricao' => '328i'],
            ['fk_montadora' => '12', 'descricao' => '330i'],
            ['fk_montadora' => '12', 'descricao' => '335'],
            ['fk_montadora' => '12', 'descricao' => '335i'],
            ['fk_montadora' => '12', 'descricao' => '420i'],
            ['fk_montadora' => '12', 'descricao' => '428i'],
            ['fk_montadora' => '12', 'descricao' => '435i'],
            ['fk_montadora' => '12', 'descricao' => '525i'],
            ['fk_montadora' => '12', 'descricao' => '528i'],
            ['fk_montadora' => '12', 'descricao' => '530i'],
            ['fk_montadora' => '12', 'descricao' => '535i'],
            ['fk_montadora' => '12', 'descricao' => '540i'],
            ['fk_montadora' => '12', 'descricao' => '545i'],
            ['fk_montadora' => '12', 'descricao' => '550i'],
            ['fk_montadora' => '12', 'descricao' => '635CSi'],
            ['fk_montadora' => '12', 'descricao' => '640i'],
            ['fk_montadora' => '12', 'descricao' => '645CI'],
            ['fk_montadora' => '12', 'descricao' => '650Ci'],
            ['fk_montadora' => '12', 'descricao' => '650i'],
            ['fk_montadora' => '12', 'descricao' => '740i'],
            ['fk_montadora' => '12', 'descricao' => '740iL'],
            ['fk_montadora' => '12', 'descricao' => '745i'],
            ['fk_montadora' => '12', 'descricao' => '750i'],
            ['fk_montadora' => '12', 'descricao' => '760Li'],
            ['fk_montadora' => '12', 'descricao' => '850Ci'],
            ['fk_montadora' => '12', 'descricao' => '850CSi'],
            ['fk_montadora' => '12', 'descricao' => 'i3'],
            ['fk_montadora' => '12', 'descricao' => 'i8'],
            ['fk_montadora' => '12', 'descricao' => 'ISETTA'],
            ['fk_montadora' => '12', 'descricao' => 'M 135i'],
            ['fk_montadora' => '12', 'descricao' => 'M235i'],
            ['fk_montadora' => '12', 'descricao' => 'M3'],
            ['fk_montadora' => '12', 'descricao' => 'M4'],
            ['fk_montadora' => '12', 'descricao' => 'M5'],
            ['fk_montadora' => '12', 'descricao' => 'M6'],
            ['fk_montadora' => '12', 'descricao' => 'X1'],
            ['fk_montadora' => '12', 'descricao' => 'X3'],
            ['fk_montadora' => '12', 'descricao' => 'X4'],
            ['fk_montadora' => '12', 'descricao' => 'X5'],
            ['fk_montadora' => '12', 'descricao' => 'X6'],
            ['fk_montadora' => '12', 'descricao' => 'Z3'],
            ['fk_montadora' => '12', 'descricao' => 'Z4'],
            ['fk_montadora' => '13', 'descricao' => 'M-10 1/2'],
            ['fk_montadora' => '13', 'descricao' => 'M-11'],
            ['fk_montadora' => '13', 'descricao' => 'M-8'],
            ['fk_montadora' => '14', 'descricao' => 'M150'],
            ['fk_montadora' => '15', 'descricao' => 'BUGGY'],
            ['fk_montadora' => '16', 'descricao' => 'DINAFLOW'],
            ['fk_montadora' => '16', 'descricao' => 'LACROSSE'],
            ['fk_montadora' => '16', 'descricao' => 'LESABRE'],
            ['fk_montadora' => '16', 'descricao' => 'PARK AVENUE'],
            ['fk_montadora' => '16', 'descricao' => 'REGAL'],
            ['fk_montadora' => '17', 'descricao' => 'CTS'],
            ['fk_montadora' => '17', 'descricao' => 'CTS-V'],
            ['fk_montadora' => '17', 'descricao' => 'DE VILLE'],
            ['fk_montadora' => '17', 'descricao' => 'ELDORADO'],
            ['fk_montadora' => '17', 'descricao' => 'ESCALADE'],
            ['fk_montadora' => '17', 'descricao' => 'FLEETWOOD'],
            ['fk_montadora' => '17', 'descricao' => 'SERIES 62'],
            ['fk_montadora' => '17', 'descricao' => 'SEVILLE'],
            ['fk_montadora' => '17', 'descricao' => 'SRX'],
            ['fk_montadora' => '18', 'descricao' => 'JEEP'],
            ['fk_montadora' => '19', 'descricao' => 'SPYDER'],
            ['fk_montadora' => '19', 'descricao' => 'SUPER 90'],
            ['fk_montadora' => '20', 'descricao' => 'CARGO'],
            ['fk_montadora' => '20', 'descricao' => 'UTILITY'],
            ['fk_montadora' => '21', 'descricao' => 'MINISTAR'],
            ['fk_montadora' => '22', 'descricao' => 'CELER'],
            ['fk_montadora' => '22', 'descricao' => 'CIELO'],
            ['fk_montadora' => '22', 'descricao' => 'FACE'],
            ['fk_montadora' => '22', 'descricao' => 'QQ'],
            ['fk_montadora' => '22', 'descricao' => 'S-18'],
            ['fk_montadora' => '22', 'descricao' => 'TIGGO'],
            ['fk_montadora' => '23', 'descricao' => 'A10'],
            ['fk_montadora' => '23', 'descricao' => 'A20'],
            ['fk_montadora' => '23', 'descricao' => 'ADVANCED DESIGN'],
            ['fk_montadora' => '23', 'descricao' => 'AGILE'],
            ['fk_montadora' => '23', 'descricao' => 'ASTRA'],
            ['fk_montadora' => '23', 'descricao' => 'ASTROVAN'],
            ['fk_montadora' => '23', 'descricao' => 'BEL AIR'],
            ['fk_montadora' => '23', 'descricao' => 'BLAZER'],
            ['fk_montadora' => '23', 'descricao' => 'BONANZA'],
            ['fk_montadora' => '23', 'descricao' => 'BRASIL'],
            ['fk_montadora' => '23', 'descricao' => 'BRASINCA'],
            ['fk_montadora' => '23', 'descricao' => 'C10'],
            ['fk_montadora' => '23', 'descricao' => 'C14'],
            ['fk_montadora' => '23', 'descricao' => 'C15'],
            ['fk_montadora' => '23', 'descricao' => 'C20'],
            ['fk_montadora' => '23', 'descricao' => 'CALIBRA'],
            ['fk_montadora' => '23', 'descricao' => 'CAMARO'],
            ['fk_montadora' => '23', 'descricao' => 'CAPRICE'],
            ['fk_montadora' => '23', 'descricao' => 'CAPTIVA'],
            ['fk_montadora' => '23', 'descricao' => 'CARAVAN'],
            ['fk_montadora' => '23', 'descricao' => 'CAVALIER'],
            ['fk_montadora' => '23', 'descricao' => 'CELTA'],
            ['fk_montadora' => '23', 'descricao' => 'CHEVELLE'],
            ['fk_montadora' => '23', 'descricao' => 'CHEVETTE'],
            ['fk_montadora' => '23', 'descricao' => 'CHEVY 500'],
            ['fk_montadora' => '23', 'descricao' => 'CHEYENNE'],
            ['fk_montadora' => '23', 'descricao' => 'CLASSIC'],
            ['fk_montadora' => '23', 'descricao' => 'COBALT'],
            ['fk_montadora' => '23', 'descricao' => 'CORSA'],
            ['fk_montadora' => '23', 'descricao' => 'CORVETTE'],
            ['fk_montadora' => '23', 'descricao' => 'CORVETTE GRAND SPORT'],
            ['fk_montadora' => '23', 'descricao' => 'CRUZE'],
            ['fk_montadora' => '23', 'descricao' => 'D10'],
            ['fk_montadora' => '23', 'descricao' => 'D20'],
            ['fk_montadora' => '23', 'descricao' => 'D40'],
            ['fk_montadora' => '23', 'descricao' => 'DE LUXE'],
            ['fk_montadora' => '23', 'descricao' => 'EL CAMINO'],
            ['fk_montadora' => '23', 'descricao' => 'FLEETMASTER'],
            ['fk_montadora' => '23', 'descricao' => 'GRAND BLAZER'],
            ['fk_montadora' => '23', 'descricao' => 'HHR'],
            ['fk_montadora' => '23', 'descricao' => 'IMPALA'],
            ['fk_montadora' => '23', 'descricao' => 'IPANEMA'],
            ['fk_montadora' => '23', 'descricao' => 'KADETT'],
            ['fk_montadora' => '23', 'descricao' => 'LUMINA'],
            ['fk_montadora' => '23', 'descricao' => 'MALIBU'],
            ['fk_montadora' => '23', 'descricao' => 'MARAJÓ'],
            ['fk_montadora' => '23', 'descricao' => 'MASTER'],
            ['fk_montadora' => '23', 'descricao' => 'MERIVA'],
            ['fk_montadora' => '23', 'descricao' => 'MONTANA'],
            ['fk_montadora' => '23', 'descricao' => 'MONZA'],
            ['fk_montadora' => '23', 'descricao' => 'OMEGA'],
            ['fk_montadora' => '23', 'descricao' => 'ONIX'],
            ['fk_montadora' => '23', 'descricao' => 'OPALA'],
            ['fk_montadora' => '23', 'descricao' => 'PICKUP'],
            ['fk_montadora' => '23', 'descricao' => 'PRISMA'],
            ['fk_montadora' => '23', 'descricao' => 'RAMONA'],
            ['fk_montadora' => '23', 'descricao' => 'S10'],
            ['fk_montadora' => '23', 'descricao' => 'SILVERADO'],
            ['fk_montadora' => '23', 'descricao' => 'SONIC'],
            ['fk_montadora' => '23', 'descricao' => 'SPACE VAN'],
            ['fk_montadora' => '23', 'descricao' => 'SPIN'],
            ['fk_montadora' => '23', 'descricao' => 'SPORT VAN'],
            ['fk_montadora' => '23', 'descricao' => 'SS'],
            ['fk_montadora' => '23', 'descricao' => 'SSR'],
            ['fk_montadora' => '23', 'descricao' => 'STYLEMASTER'],
            ['fk_montadora' => '23', 'descricao' => 'SUBURBAN'],
            ['fk_montadora' => '23', 'descricao' => 'SUPREMA'],
            ['fk_montadora' => '23', 'descricao' => 'TAHOE'],
            ['fk_montadora' => '23', 'descricao' => 'TIGRA'],
            ['fk_montadora' => '23', 'descricao' => 'TRACKER'],
            ['fk_montadora' => '23', 'descricao' => 'TRAFIC'],
            ['fk_montadora' => '23', 'descricao' => 'TRAILBLAZER'],
            ['fk_montadora' => '23', 'descricao' => 'TRAVERSE'],
            ['fk_montadora' => '23', 'descricao' => 'VECTRA'],
            ['fk_montadora' => '23', 'descricao' => 'VERANEIO'],
            ['fk_montadora' => '23', 'descricao' => 'ZAFIRA'],
            ['fk_montadora' => '23', 'descricao' => 'A10'],
            ['fk_montadora' => '23', 'descricao' => 'A20'],
            ['fk_montadora' => '23', 'descricao' => 'ADVANCED DESIGN'],
            ['fk_montadora' => '23', 'descricao' => 'AGILE'],
            ['fk_montadora' => '23', 'descricao' => 'ASTRA'],
            ['fk_montadora' => '23', 'descricao' => 'ASTROVAN'],
            ['fk_montadora' => '23', 'descricao' => 'BEL AIR'],
            ['fk_montadora' => '23', 'descricao' => 'BLAZER'],
            ['fk_montadora' => '23', 'descricao' => 'BONANZA'],
            ['fk_montadora' => '23', 'descricao' => 'BRASIL'],
            ['fk_montadora' => '23', 'descricao' => 'BRASINCA'],
            ['fk_montadora' => '23', 'descricao' => 'C10'],
            ['fk_montadora' => '23', 'descricao' => 'C14'],
            ['fk_montadora' => '23', 'descricao' => 'C15'],
            ['fk_montadora' => '23', 'descricao' => 'C20'],
            ['fk_montadora' => '23', 'descricao' => 'CALIBRA'],
            ['fk_montadora' => '23', 'descricao' => 'CAMARO'],
            ['fk_montadora' => '23', 'descricao' => 'CAPRICE'],
            ['fk_montadora' => '23', 'descricao' => 'CAPTIVA'],
            ['fk_montadora' => '23', 'descricao' => 'CARAVAN'],
            ['fk_montadora' => '23', 'descricao' => 'CAVALIER'],
            ['fk_montadora' => '23', 'descricao' => 'CELTA'],
            ['fk_montadora' => '23', 'descricao' => 'CHEVELLE'],
            ['fk_montadora' => '23', 'descricao' => 'CHEVETTE'],
            ['fk_montadora' => '23', 'descricao' => 'CHEVY 500'],
            ['fk_montadora' => '23', 'descricao' => 'CHEYENNE'],
            ['fk_montadora' => '23', 'descricao' => 'CLASSIC'],
            ['fk_montadora' => '23', 'descricao' => 'COBALT'],
            ['fk_montadora' => '23', 'descricao' => 'CORSA'],
            ['fk_montadora' => '23', 'descricao' => 'CORVETTE'],
            ['fk_montadora' => '23', 'descricao' => 'CORVETTE GRAND SPORT'],
            ['fk_montadora' => '23', 'descricao' => 'CRUZE'],
            ['fk_montadora' => '23', 'descricao' => 'D10'],
            ['fk_montadora' => '23', 'descricao' => 'D20'],
            ['fk_montadora' => '23', 'descricao' => 'D40'],
            ['fk_montadora' => '23', 'descricao' => 'DE LUXE'],
            ['fk_montadora' => '23', 'descricao' => 'EL CAMINO'],
            ['fk_montadora' => '23', 'descricao' => 'FLEETMASTER'],
            ['fk_montadora' => '23', 'descricao' => 'GRAND BLAZER'],
            ['fk_montadora' => '23', 'descricao' => 'HHR'],
            ['fk_montadora' => '23', 'descricao' => 'IMPALA'],
            ['fk_montadora' => '23', 'descricao' => 'IPANEMA'],
            ['fk_montadora' => '23', 'descricao' => 'KADETT'],
            ['fk_montadora' => '23', 'descricao' => 'LUMINA'],
            ['fk_montadora' => '23', 'descricao' => 'MALIBU'],
            ['fk_montadora' => '23', 'descricao' => 'MARAJÓ'],
            ['fk_montadora' => '23', 'descricao' => 'MASTER'],
            ['fk_montadora' => '23', 'descricao' => 'MERIVA'],
            ['fk_montadora' => '23', 'descricao' => 'MONTANA'],
            ['fk_montadora' => '23', 'descricao' => 'MONZA'],
            ['fk_montadora' => '23', 'descricao' => 'OMEGA'],
            ['fk_montadora' => '23', 'descricao' => 'ONIX'],
            ['fk_montadora' => '23', 'descricao' => 'OPALA'],
            ['fk_montadora' => '23', 'descricao' => 'PICKUP'],
            ['fk_montadora' => '23', 'descricao' => 'PRISMA'],
            ['fk_montadora' => '23', 'descricao' => 'RAMONA'],
            ['fk_montadora' => '23', 'descricao' => 'S10'],
            ['fk_montadora' => '23', 'descricao' => 'SILVERADO'],
            ['fk_montadora' => '23', 'descricao' => 'SONIC'],
            ['fk_montadora' => '23', 'descricao' => 'SPACE VAN'],
            ['fk_montadora' => '23', 'descricao' => 'SPIN'],
            ['fk_montadora' => '23', 'descricao' => 'SPORT VAN'],
            ['fk_montadora' => '23', 'descricao' => 'SS'],
            ['fk_montadora' => '23', 'descricao' => 'SSR'],
            ['fk_montadora' => '23', 'descricao' => 'STYLEMASTER'],
            ['fk_montadora' => '23', 'descricao' => 'SUBURBAN'],
            ['fk_montadora' => '23', 'descricao' => 'SUPREMA'],
            ['fk_montadora' => '23', 'descricao' => 'TAHOE'],
            ['fk_montadora' => '23', 'descricao' => 'TIGRA'],
            ['fk_montadora' => '23', 'descricao' => 'TRACKER'],
            ['fk_montadora' => '23', 'descricao' => 'TRAFIC'],
            ['fk_montadora' => '23', 'descricao' => 'TRAILBLAZER'],
            ['fk_montadora' => '23', 'descricao' => 'TRAVERSE'],
            ['fk_montadora' => '23', 'descricao' => 'VECTRA'],
            ['fk_montadora' => '23', 'descricao' => 'VERANEIO'],
            ['fk_montadora' => '23', 'descricao' => 'ZAFIRA'],
            ['fk_montadora' => '24', 'descricao' => '300 C'],
            ['fk_montadora' => '24', 'descricao' => '300 M'],
            ['fk_montadora' => '24', 'descricao' => 'CARAVAN'],
            ['fk_montadora' => '24', 'descricao' => 'CORDOBA'],
            ['fk_montadora' => '24', 'descricao' => 'ESPLANADA'],
            ['fk_montadora' => '24', 'descricao' => 'GRAND CARAVAN'],
            ['fk_montadora' => '24', 'descricao' => 'NEON'],
            ['fk_montadora' => '24', 'descricao' => 'PT CRUISER'],
            ['fk_montadora' => '24', 'descricao' => 'SEBRING'],
            ['fk_montadora' => '24', 'descricao' => 'STRATUS'],
            ['fk_montadora' => '24', 'descricao' => 'TOWN & COUNTRY'],
            ['fk_montadora' => '25', 'descricao' => 'AIRCROSS'],
            ['fk_montadora' => '25', 'descricao' => 'BERLINGO'],
            ['fk_montadora' => '25', 'descricao' => 'C3'],
            ['fk_montadora' => '25', 'descricao' => 'C3 SONORA'],
            ['fk_montadora' => '25', 'descricao' => 'C4'],
            ['fk_montadora' => '25', 'descricao' => 'C4 LOUNGE'],
            ['fk_montadora' => '25', 'descricao' => 'C4 PICASSO'],
            ['fk_montadora' => '25', 'descricao' => 'C5'],
            ['fk_montadora' => '25', 'descricao' => 'C6'],
            ['fk_montadora' => '25', 'descricao' => 'C8'],
            ['fk_montadora' => '25', 'descricao' => 'DS3'],
            ['fk_montadora' => '25', 'descricao' => 'DS4'],
            ['fk_montadora' => '25', 'descricao' => 'DS5'],
            ['fk_montadora' => '25', 'descricao' => 'EVASION'],
            ['fk_montadora' => '25', 'descricao' => 'GRAND C4'],
            ['fk_montadora' => '25', 'descricao' => 'JUMPER'],
            ['fk_montadora' => '25', 'descricao' => 'TRACTION AVANT'],
            ['fk_montadora' => '25', 'descricao' => 'XANTIA'],
            ['fk_montadora' => '25', 'descricao' => 'XM'],
            ['fk_montadora' => '25', 'descricao' => 'XSARA'],
            ['fk_montadora' => '25', 'descricao' => 'XSARA PICASSO'],
            ['fk_montadora' => '26', 'descricao' => '828'],
            ['fk_montadora' => '27', 'descricao' => 'ESPERO'],
            ['fk_montadora' => '27', 'descricao' => 'LANOS'],
            ['fk_montadora' => '28', 'descricao' => 'FEROZA'],
            ['fk_montadora' => '28', 'descricao' => 'GRAN MOVE'],
            ['fk_montadora' => '28', 'descricao' => 'TERIOS'],
            ['fk_montadora' => '29', 'descricao' => 'DE SOTO'],
            ['fk_montadora' => '30', 'descricao' => 'DMC-12'],
            ['fk_montadora' => '31', 'descricao' => 'BELCAR'],
            ['fk_montadora' => '31', 'descricao' => 'FISSORE'],
            ['fk_montadora' => '32', 'descricao' => 'CALIBER'],
            ['fk_montadora' => '32', 'descricao' => 'CHALLENGER'],
            ['fk_montadora' => '32', 'descricao' => 'CHARGER'],
            ['fk_montadora' => '32', 'descricao' => 'DAKOTA'],
            ['fk_montadora' => '32', 'descricao' => 'DART'],
            ['fk_montadora' => '32', 'descricao' => 'DURANGO'],
            ['fk_montadora' => '32', 'descricao' => 'GRAND CARAVAN'],
            ['fk_montadora' => '32', 'descricao' => 'JOURNEY'],
            ['fk_montadora' => '32', 'descricao' => 'LE BARON'],
            ['fk_montadora' => '32', 'descricao' => 'MAGNUM'],
            ['fk_montadora' => '32', 'descricao' => 'NITRO'],
            ['fk_montadora' => '32', 'descricao' => 'POLARA'],
            ['fk_montadora' => '32', 'descricao' => 'RAM'],
            ['fk_montadora' => '32', 'descricao' => 'STEALTH'],
            ['fk_montadora' => '32', 'descricao' => 'TRAZO'],
            ['fk_montadora' => '32', 'descricao' => 'VIPER'],
            ['fk_montadora' => '33', 'descricao' => 'FURGÃO'],
            ['fk_montadora' => '33', 'descricao' => 'M100'],
            ['fk_montadora' => '33', 'descricao' => 'PICAPE CABINE DUPLA'],
            ['fk_montadora' => '33', 'descricao' => 'PICAPE CAÇAMBA CURTA'],
            ['fk_montadora' => '33', 'descricao' => 'PICAPE CAÇAMBA LONGA'],
            ['fk_montadora' => '33', 'descricao' => 'PICAPE CAÇAMBA LONGA BAÚ'],
            ['fk_montadora' => '33', 'descricao' => 'PICAPE PLUTUS'],
            ['fk_montadora' => '33', 'descricao' => 'PICAPE START CABINE DUPLA'],
            ['fk_montadora' => '33', 'descricao' => 'PICAPE START LONGA'],
            ['fk_montadora' => '33', 'descricao' => 'VAN'],
            ['fk_montadora' => '33', 'descricao' => 'VAN START'],
            ['fk_montadora' => '34', 'descricao' => 'BUGGY'],
            ['fk_montadora' => '35', 'descricao' => 'ENGESA'],
            ['fk_montadora' => '35', 'descricao' => 'ENGESA 4'],
            ['fk_montadora' => '36', 'descricao' => 'CAMPER'],
            ['fk_montadora' => '36', 'descricao' => 'SUPER 90'],
            ['fk_montadora' => '37', 'descricao' => 'NAJA ONE'],
            ['fk_montadora' => '38', 'descricao' => '308'],
            ['fk_montadora' => '38', 'descricao' => '328 GTB'],
            ['fk_montadora' => '38', 'descricao' => '348'],
            ['fk_montadora' => '38', 'descricao' => '458 ITALIA'],
            ['fk_montadora' => '38', 'descricao' => '458 SPECIALE'],
            ['fk_montadora' => '38', 'descricao' => '458 SPIDER'],
            ['fk_montadora' => '38', 'descricao' => '488 GTB'],
            ['fk_montadora' => '38', 'descricao' => '599 GTB'],
            ['fk_montadora' => '38', 'descricao' => '612'],
            ['fk_montadora' => '38', 'descricao' => 'CALIFORNIA'],
            ['fk_montadora' => '38', 'descricao' => 'F12BERLINETTA'],
            ['fk_montadora' => '38', 'descricao' => 'F355'],
            ['fk_montadora' => '38', 'descricao' => 'F355 F1'],
            ['fk_montadora' => '38', 'descricao' => 'F360'],
            ['fk_montadora' => '38', 'descricao' => 'F430'],
            ['fk_montadora' => '38', 'descricao' => 'F456'],
            ['fk_montadora' => '38', 'descricao' => 'FF'],
            ['fk_montadora' => '39', 'descricao' => '147'],
            ['fk_montadora' => '39', 'descricao' => '500'],
            ['fk_montadora' => '39', 'descricao' => '600'],
            ['fk_montadora' => '39', 'descricao' => 'BRAVA'],
            ['fk_montadora' => '39', 'descricao' => 'BRAVO'],
            ['fk_montadora' => '39', 'descricao' => 'CINQUECENTO'],
            ['fk_montadora' => '39', 'descricao' => 'COUPÉ'],
            ['fk_montadora' => '39', 'descricao' => 'DOBLÒ'],
            ['fk_montadora' => '39', 'descricao' => 'DUCATO'],
            ['fk_montadora' => '39', 'descricao' => 'ELBA'],
            ['fk_montadora' => '39', 'descricao' => 'FIORINO'],
            ['fk_montadora' => '39', 'descricao' => 'FREEMONT'],
            ['fk_montadora' => '39', 'descricao' => 'GRAND SIENA'],
            ['fk_montadora' => '39', 'descricao' => 'IDEA'],
            ['fk_montadora' => '39', 'descricao' => 'LINEA'],
            ['fk_montadora' => '39', 'descricao' => 'MAREA'],
            ['fk_montadora' => '39', 'descricao' => 'OGGI'],
            ['fk_montadora' => '39', 'descricao' => 'PALIO'],
            ['fk_montadora' => '39', 'descricao' => 'PANORAMA'],
            ['fk_montadora' => '39', 'descricao' => 'PREMIO'],
            ['fk_montadora' => '39', 'descricao' => 'PUNTO'],
            ['fk_montadora' => '39', 'descricao' => 'SIENA'],
            ['fk_montadora' => '39', 'descricao' => 'SPAZIO'],
            ['fk_montadora' => '39', 'descricao' => 'STILO'],
            ['fk_montadora' => '39', 'descricao' => 'STRADA'],
            ['fk_montadora' => '39', 'descricao' => 'TEMPRA'],
            ['fk_montadora' => '39', 'descricao' => 'TIPO'],
            ['fk_montadora' => '39', 'descricao' => 'UNO'],
            ['fk_montadora' => '39', 'descricao' => '147'],
            ['fk_montadora' => '39', 'descricao' => '500'],
            ['fk_montadora' => '39', 'descricao' => '600'],
            ['fk_montadora' => '39', 'descricao' => 'BRAVA'],
            ['fk_montadora' => '39', 'descricao' => 'BRAVO'],
            ['fk_montadora' => '39', 'descricao' => 'CINQUECENTO'],
            ['fk_montadora' => '39', 'descricao' => 'COUPÉ'],
            ['fk_montadora' => '39', 'descricao' => 'DOBLÒ'],
            ['fk_montadora' => '39', 'descricao' => 'DUCATO'],
            ['fk_montadora' => '39', 'descricao' => 'ELBA'],
            ['fk_montadora' => '39', 'descricao' => 'FIORINO'],
            ['fk_montadora' => '39', 'descricao' => 'FREEMONT'],
            ['fk_montadora' => '39', 'descricao' => 'GRAND SIENA'],
            ['fk_montadora' => '39', 'descricao' => 'IDEA'],
            ['fk_montadora' => '39', 'descricao' => 'LINEA'],
            ['fk_montadora' => '39', 'descricao' => 'MAREA'],
            ['fk_montadora' => '39', 'descricao' => 'OGGI'],
            ['fk_montadora' => '39', 'descricao' => 'PALIO'],
            ['fk_montadora' => '39', 'descricao' => 'PANORAMA'],
            ['fk_montadora' => '39', 'descricao' => 'PREMIO'],
            ['fk_montadora' => '39', 'descricao' => 'PUNTO'],
            ['fk_montadora' => '39', 'descricao' => 'SIENA'],
            ['fk_montadora' => '39', 'descricao' => 'SPAZIO'],
            ['fk_montadora' => '39', 'descricao' => 'STILO'],
            ['fk_montadora' => '39', 'descricao' => 'STRADA'],
            ['fk_montadora' => '39', 'descricao' => 'TEMPRA'],
            ['fk_montadora' => '39', 'descricao' => 'TIPO'],
            ['fk_montadora' => '39', 'descricao' => 'UNO'],
            ['fk_montadora' => '40', 'descricao' => 'A'],
            ['fk_montadora' => '40', 'descricao' => 'BELINA'],
            ['fk_montadora' => '40', 'descricao' => 'CLUB WAGON'],
            ['fk_montadora' => '40', 'descricao' => 'CORCEL'],
            ['fk_montadora' => '40', 'descricao' => 'CORCEL II'],
            ['fk_montadora' => '40', 'descricao' => 'COURIER'],
            ['fk_montadora' => '40', 'descricao' => 'CROWN VICTORIA'],
            ['fk_montadora' => '40', 'descricao' => 'CUPÊ'],
            ['fk_montadora' => '40', 'descricao' => 'CUSTOM'],
            ['fk_montadora' => '40', 'descricao' => 'DEL REY'],
            ['fk_montadora' => '40', 'descricao' => 'ECOSPORT'],
            ['fk_montadora' => '40', 'descricao' => 'EDGE'],
            ['fk_montadora' => '40', 'descricao' => 'ESCAPE'],
            ['fk_montadora' => '40', 'descricao' => 'ESCORT'],
            ['fk_montadora' => '40', 'descricao' => 'EXPEDITION'],
            ['fk_montadora' => '40', 'descricao' => 'EXPLORER'],
            ['fk_montadora' => '40', 'descricao' => 'F-1'],
            ['fk_montadora' => '40', 'descricao' => 'F-100'],
            ['fk_montadora' => '40', 'descricao' => 'F-1000'],
            ['fk_montadora' => '40', 'descricao' => 'F-150'],
            ['fk_montadora' => '40', 'descricao' => 'F-250'],
            ['fk_montadora' => '40', 'descricao' => 'F-350'],
            ['fk_montadora' => '40', 'descricao' => 'F-4000'],
            ['fk_montadora' => '40', 'descricao' => 'F-75'],
            ['fk_montadora' => '40', 'descricao' => 'FAIRLANE'],
            ['fk_montadora' => '40', 'descricao' => 'FIESTA'],
            ['fk_montadora' => '40', 'descricao' => 'FLEX'],
            ['fk_montadora' => '40', 'descricao' => 'FOCUS'],
            ['fk_montadora' => '40', 'descricao' => 'FUSION'],
            ['fk_montadora' => '40', 'descricao' => 'GALAXIE'],
            ['fk_montadora' => '40', 'descricao' => 'IBIZA'],
            ['fk_montadora' => '40', 'descricao' => 'JEEP'],
            ['fk_montadora' => '40', 'descricao' => 'KA'],
            ['fk_montadora' => '40', 'descricao' => 'KA +'],
            ['fk_montadora' => '40', 'descricao' => 'LANDAU'],
            ['fk_montadora' => '40', 'descricao' => 'MAVERICK'],
            ['fk_montadora' => '40', 'descricao' => 'MONDEO'],
            ['fk_montadora' => '40', 'descricao' => 'MUSTANG'],
            ['fk_montadora' => '40', 'descricao' => 'MUSTANG V6'],
            ['fk_montadora' => '40', 'descricao' => 'PAMPA'],
            ['fk_montadora' => '40', 'descricao' => 'PHAETON'],
            ['fk_montadora' => '40', 'descricao' => 'RANCHERO'],
            ['fk_montadora' => '40', 'descricao' => 'RANGER'],
            ['fk_montadora' => '40', 'descricao' => 'ROYALE'],
            ['fk_montadora' => '40', 'descricao' => 'RURAL'],
            ['fk_montadora' => '40', 'descricao' => 'SUPER DELUXE'],
            ['fk_montadora' => '40', 'descricao' => 'T'],
            ['fk_montadora' => '40', 'descricao' => 'TAURUS'],
            ['fk_montadora' => '40', 'descricao' => 'THUNDERBIRD'],
            ['fk_montadora' => '40', 'descricao' => 'TRANSIT'],
            ['fk_montadora' => '40', 'descricao' => 'TUDOR'],
            ['fk_montadora' => '40', 'descricao' => 'VERONA'],
            ['fk_montadora' => '40', 'descricao' => 'VERSAILLES'],
            ['fk_montadora' => '40', 'descricao' => 'WINDSTAR'],
            ['fk_montadora' => '40', 'descricao' => 'A'],
            ['fk_montadora' => '40', 'descricao' => 'BELINA'],
            ['fk_montadora' => '40', 'descricao' => 'CLUB WAGON'],
            ['fk_montadora' => '40', 'descricao' => 'CORCEL'],
            ['fk_montadora' => '40', 'descricao' => 'CORCEL II'],
            ['fk_montadora' => '40', 'descricao' => 'COURIER'],
            ['fk_montadora' => '40', 'descricao' => 'CROWN VICTORIA'],
            ['fk_montadora' => '40', 'descricao' => 'CUPÊ'],
            ['fk_montadora' => '40', 'descricao' => 'CUSTOM'],
            ['fk_montadora' => '40', 'descricao' => 'DEL REY'],
            ['fk_montadora' => '40', 'descricao' => 'ECOSPORT'],
            ['fk_montadora' => '40', 'descricao' => 'EDGE'],
            ['fk_montadora' => '40', 'descricao' => 'ESCAPE'],
            ['fk_montadora' => '40', 'descricao' => 'ESCORT'],
            ['fk_montadora' => '40', 'descricao' => 'EXPEDITION'],
            ['fk_montadora' => '40', 'descricao' => 'EXPLORER'],
            ['fk_montadora' => '40', 'descricao' => 'F-1'],
            ['fk_montadora' => '40', 'descricao' => 'F-100'],
            ['fk_montadora' => '40', 'descricao' => 'F-1000'],
            ['fk_montadora' => '40', 'descricao' => 'F-150'],
            ['fk_montadora' => '40', 'descricao' => 'F-250'],
            ['fk_montadora' => '40', 'descricao' => 'F-350'],
            ['fk_montadora' => '40', 'descricao' => 'F-4000'],
            ['fk_montadora' => '40', 'descricao' => 'F-75'],
            ['fk_montadora' => '40', 'descricao' => 'FAIRLANE'],
            ['fk_montadora' => '40', 'descricao' => 'FIESTA'],
            ['fk_montadora' => '40', 'descricao' => 'FLEX'],
            ['fk_montadora' => '40', 'descricao' => 'FOCUS'],
            ['fk_montadora' => '40', 'descricao' => 'FUSION'],
            ['fk_montadora' => '40', 'descricao' => 'GALAXIE'],
            ['fk_montadora' => '40', 'descricao' => 'IBIZA'],
            ['fk_montadora' => '40', 'descricao' => 'JEEP'],
            ['fk_montadora' => '40', 'descricao' => 'KA'],
            ['fk_montadora' => '40', 'descricao' => 'KA +'],
            ['fk_montadora' => '40', 'descricao' => 'LANDAU'],
            ['fk_montadora' => '40', 'descricao' => 'MAVERICK'],
            ['fk_montadora' => '40', 'descricao' => 'MONDEO'],
            ['fk_montadora' => '40', 'descricao' => 'MUSTANG'],
            ['fk_montadora' => '40', 'descricao' => 'MUSTANG V6'],
            ['fk_montadora' => '40', 'descricao' => 'PAMPA'],
            ['fk_montadora' => '40', 'descricao' => 'PHAETON'],
            ['fk_montadora' => '40', 'descricao' => 'RANCHERO'],
            ['fk_montadora' => '40', 'descricao' => 'RANGER'],
            ['fk_montadora' => '40', 'descricao' => 'ROYALE'],
            ['fk_montadora' => '40', 'descricao' => 'RURAL'],
            ['fk_montadora' => '40', 'descricao' => 'SUPER DELUXE'],
            ['fk_montadora' => '40', 'descricao' => 'T'],
            ['fk_montadora' => '40', 'descricao' => 'TAURUS'],
            ['fk_montadora' => '40', 'descricao' => 'THUNDERBIRD'],
            ['fk_montadora' => '40', 'descricao' => 'TRANSIT'],
            ['fk_montadora' => '40', 'descricao' => 'TUDOR'],
            ['fk_montadora' => '40', 'descricao' => 'VERONA'],
            ['fk_montadora' => '40', 'descricao' => 'VERSAILLES'],
            ['fk_montadora' => '40', 'descricao' => 'WINDSTAR'],
            ['fk_montadora' => '41', 'descricao' => 'AUMARK 3.5'],
            ['fk_montadora' => '42', 'descricao' => '2000W'],
            ['fk_montadora' => '43', 'descricao' => 'EC7'],
            ['fk_montadora' => '43', 'descricao' => 'GC2'],
            ['fk_montadora' => '44', 'descricao' => 'STORM'],
            ['fk_montadora' => '45', 'descricao' => '3500 HD'],
            ['fk_montadora' => '45', 'descricao' => 'BLAZER'],
            ['fk_montadora' => '45', 'descricao' => 'ENVOY'],
            ['fk_montadora' => '45', 'descricao' => 'SIERRA'],
            ['fk_montadora' => '45', 'descricao' => 'SILVERADO'],
            ['fk_montadora' => '45', 'descricao' => 'SONOMA'],
            ['fk_montadora' => '46', 'descricao' => 'BR-800'],
            ['fk_montadora' => '46', 'descricao' => 'SUPERMINI'],
            ['fk_montadora' => '46', 'descricao' => 'X12'],
            ['fk_montadora' => '47', 'descricao' => 'TOWNER'],
            ['fk_montadora' => '47', 'descricao' => 'TOWNER JR'],
            ['fk_montadora' => '48', 'descricao' => 'ACCORD'],
            ['fk_montadora' => '48', 'descricao' => 'CITY'],
            ['fk_montadora' => '48', 'descricao' => 'CIVIC'],
            ['fk_montadora' => '48', 'descricao' => 'CRV'],
            ['fk_montadora' => '48', 'descricao' => 'FIT'],
            ['fk_montadora' => '48', 'descricao' => 'HR-V'],
            ['fk_montadora' => '48', 'descricao' => 'LEGEND'],
            ['fk_montadora' => '48', 'descricao' => 'PRELUDE'],
            ['fk_montadora' => '48', 'descricao' => 'ACCORD'],
            ['fk_montadora' => '48', 'descricao' => 'CITY'],
            ['fk_montadora' => '48', 'descricao' => 'CIVIC'],
            ['fk_montadora' => '48', 'descricao' => 'CRV'],
            ['fk_montadora' => '48', 'descricao' => 'FIT'],
            ['fk_montadora' => '48', 'descricao' => 'HR-V'],
            ['fk_montadora' => '48', 'descricao' => 'LEGEND'],
            ['fk_montadora' => '48', 'descricao' => 'PRELUDE'],
            ['fk_montadora' => '49', 'descricao' => 'HORNET'],
            ['fk_montadora' => '50', 'descricao' => 'H1'],
            ['fk_montadora' => '50', 'descricao' => 'H2'],
            ['fk_montadora' => '50', 'descricao' => 'H3'],
            ['fk_montadora' => '51', 'descricao' => 'ACCENT'],
            ['fk_montadora' => '51', 'descricao' => 'ATOS'],
            ['fk_montadora' => '51', 'descricao' => 'AZERA'],
            ['fk_montadora' => '51', 'descricao' => 'COUPÊ'],
            ['fk_montadora' => '51', 'descricao' => 'ELANTRA'],
            ['fk_montadora' => '51', 'descricao' => 'EQUUS'],
            ['fk_montadora' => '51', 'descricao' => 'GALLOPER'],
            ['fk_montadora' => '51', 'descricao' => 'GENESIS'],
            ['fk_montadora' => '51', 'descricao' => 'GRAND SANTA FÉ'],
            ['fk_montadora' => '51', 'descricao' => 'H1 STAREX'],
            ['fk_montadora' => '51', 'descricao' => 'H100'],
            ['fk_montadora' => '51', 'descricao' => 'HB20'],
            ['fk_montadora' => '51', 'descricao' => 'HB20S'],
            ['fk_montadora' => '51', 'descricao' => 'HB20X'],
            ['fk_montadora' => '51', 'descricao' => 'HR'],
            ['fk_montadora' => '51', 'descricao' => 'I30'],
            ['fk_montadora' => '51', 'descricao' => 'I30 CW'],
            ['fk_montadora' => '51', 'descricao' => 'IX35'],
            ['fk_montadora' => '51', 'descricao' => 'SANTA FÉ'],
            ['fk_montadora' => '51', 'descricao' => 'SONATA'],
            ['fk_montadora' => '51', 'descricao' => 'TERRACAN'],
            ['fk_montadora' => '51', 'descricao' => 'TIBURON'],
            ['fk_montadora' => '51', 'descricao' => 'TUCSON'],
            ['fk_montadora' => '51', 'descricao' => 'VELOSTER'],
            ['fk_montadora' => '51', 'descricao' => 'VERA CRUZ'],
            ['fk_montadora' => '51', 'descricao' => 'ACCENT'],
            ['fk_montadora' => '51', 'descricao' => 'ATOS'],
            ['fk_montadora' => '51', 'descricao' => 'AZERA'],
            ['fk_montadora' => '51', 'descricao' => 'COUPÊ'],
            ['fk_montadora' => '51', 'descricao' => 'ELANTRA'],
            ['fk_montadora' => '51', 'descricao' => 'EQUUS'],
            ['fk_montadora' => '51', 'descricao' => 'GALLOPER'],
            ['fk_montadora' => '51', 'descricao' => 'GENESIS'],
            ['fk_montadora' => '51', 'descricao' => 'GRAND SANTA FÉ'],
            ['fk_montadora' => '51', 'descricao' => 'H1 STAREX'],
            ['fk_montadora' => '51', 'descricao' => 'H100'],
            ['fk_montadora' => '51', 'descricao' => 'HB20'],
            ['fk_montadora' => '51', 'descricao' => 'HB20S'],
            ['fk_montadora' => '51', 'descricao' => 'HB20X'],
            ['fk_montadora' => '51', 'descricao' => 'HR'],
            ['fk_montadora' => '51', 'descricao' => 'I30'],
            ['fk_montadora' => '51', 'descricao' => 'I30 CW'],
            ['fk_montadora' => '51', 'descricao' => 'IX35'],
            ['fk_montadora' => '51', 'descricao' => 'SANTA FÉ'],
            ['fk_montadora' => '51', 'descricao' => 'SONATA'],
            ['fk_montadora' => '51', 'descricao' => 'TERRACAN'],
            ['fk_montadora' => '51', 'descricao' => 'TIBURON'],
            ['fk_montadora' => '51', 'descricao' => 'TUCSON'],
            ['fk_montadora' => '51', 'descricao' => 'VELOSTER'],
            ['fk_montadora' => '51', 'descricao' => 'VERA CRUZ'],
            ['fk_montadora' => '52', 'descricao' => 'EX35'],
            ['fk_montadora' => '52', 'descricao' => 'FX35'],
            ['fk_montadora' => '52', 'descricao' => 'FX37'],
            ['fk_montadora' => '52', 'descricao' => 'FX45'],
            ['fk_montadora' => '52', 'descricao' => 'FX50'],
            ['fk_montadora' => '52', 'descricao' => 'QX56'],
            ['fk_montadora' => '52', 'descricao' => 'QX70'],
            ['fk_montadora' => '53', 'descricao' => 'KB2'],
            ['fk_montadora' => '54', 'descricao' => 'DAILY'],
            ['fk_montadora' => '55', 'descricao' => 'J2'],
            ['fk_montadora' => '55', 'descricao' => 'J3'],
            ['fk_montadora' => '55', 'descricao' => 'J5'],
            ['fk_montadora' => '55', 'descricao' => 'J6'],
            ['fk_montadora' => '55', 'descricao' => 'T140'],
            ['fk_montadora' => '55', 'descricao' => 'T6'],
            ['fk_montadora' => '55', 'descricao' => 'T8'],
            ['fk_montadora' => '56', 'descricao' => 'E-TYPE'],
            ['fk_montadora' => '56', 'descricao' => 'F-TYPE'],
            ['fk_montadora' => '56', 'descricao' => 'S-TYPE'],
            ['fk_montadora' => '56', 'descricao' => 'XE'],
            ['fk_montadora' => '56', 'descricao' => 'XF'],
            ['fk_montadora' => '56', 'descricao' => 'XFR'],
            ['fk_montadora' => '56', 'descricao' => 'XJ'],
            ['fk_montadora' => '56', 'descricao' => 'XJ6'],
            ['fk_montadora' => '56', 'descricao' => 'XJ8'],
            ['fk_montadora' => '56', 'descricao' => 'XJ-S'],
            ['fk_montadora' => '56', 'descricao' => 'XK 120'],
            ['fk_montadora' => '56', 'descricao' => 'XK8'],
            ['fk_montadora' => '56', 'descricao' => 'XKR'],
            ['fk_montadora' => '56', 'descricao' => 'XKR-S'],
            ['fk_montadora' => '56', 'descricao' => 'X-TYPE'],
            ['fk_montadora' => '57', 'descricao' => 'CHEROKEE'],
            ['fk_montadora' => '57', 'descricao' => 'CJ 5'],
            ['fk_montadora' => '57', 'descricao' => 'COMMANDER'],
            ['fk_montadora' => '57', 'descricao' => 'COMPASS'],
            ['fk_montadora' => '57', 'descricao' => 'GRAND CHEROKEE'],
            ['fk_montadora' => '57', 'descricao' => 'PATRIOT'],
            ['fk_montadora' => '57', 'descricao' => 'RENEGADE'],
            ['fk_montadora' => '57', 'descricao' => 'WRANGLER'],
            ['fk_montadora' => '58', 'descricao' => 'TOPIC'],
            ['fk_montadora' => '59', 'descricao' => 'MONTEZ'],
            ['fk_montadora' => '60', 'descricao' => 'HENRY J'],
            ['fk_montadora' => '61', 'descricao' => 'BESTA'],
            ['fk_montadora' => '61', 'descricao' => 'BONGO'],
            ['fk_montadora' => '61', 'descricao' => 'CADENZA'],
            ['fk_montadora' => '61', 'descricao' => 'CARENS'],
            ['fk_montadora' => '61', 'descricao' => 'CARNIVAL'],
            ['fk_montadora' => '61', 'descricao' => 'CERATO'],
            ['fk_montadora' => '61', 'descricao' => 'CLARUS'],
            ['fk_montadora' => '61', 'descricao' => 'MAGENTIS'],
            ['fk_montadora' => '61', 'descricao' => 'MOHAVE'],
            ['fk_montadora' => '61', 'descricao' => 'OPIRUS'],
            ['fk_montadora' => '61', 'descricao' => 'OPTIMA'],
            ['fk_montadora' => '61', 'descricao' => 'PICANTO'],
            ['fk_montadora' => '61', 'descricao' => 'QUORIS'],
            ['fk_montadora' => '61', 'descricao' => 'RIO'],
            ['fk_montadora' => '61', 'descricao' => 'SHUMA'],
            ['fk_montadora' => '61', 'descricao' => 'SORENTO'],
            ['fk_montadora' => '61', 'descricao' => 'SOUL'],
            ['fk_montadora' => '61', 'descricao' => 'SPORTAGE'],
            ['fk_montadora' => '62', 'descricao' => 'NIVA'],
            ['fk_montadora' => '63', 'descricao' => 'AVENTADOR'],
            ['fk_montadora' => '63', 'descricao' => 'GALLARDO'],
            ['fk_montadora' => '63', 'descricao' => 'HURACÁN'],
            ['fk_montadora' => '64', 'descricao' => 'DEFENDER'],
            ['fk_montadora' => '64', 'descricao' => 'DISCOVERY'],
            ['fk_montadora' => '64', 'descricao' => 'DISCOVERY 2'],
            ['fk_montadora' => '64', 'descricao' => 'DISCOVERY 3'],
            ['fk_montadora' => '64', 'descricao' => 'DISCOVERY 4'],
            ['fk_montadora' => '64', 'descricao' => 'DISCOVERY SPORT'],
            ['fk_montadora' => '64', 'descricao' => 'FREELANDER'],
            ['fk_montadora' => '64', 'descricao' => 'FREELANDER 2'],
            ['fk_montadora' => '64', 'descricao' => 'RANGE ROVER'],
            ['fk_montadora' => '64', 'descricao' => 'RANGE ROVER EVOQUE'],
            ['fk_montadora' => '64', 'descricao' => 'RANGE ROVER SPORT'],
            ['fk_montadora' => '64', 'descricao' => 'RANGE ROVER VOGUE'],
            ['fk_montadora' => '64', 'descricao' => 'SÉRIE I'],
            ['fk_montadora' => '65', 'descricao' => 'X8'],
            ['fk_montadora' => '66', 'descricao' => 'CT200H'],
            ['fk_montadora' => '66', 'descricao' => 'ES'],
            ['fk_montadora' => '66', 'descricao' => 'ES 330'],
            ['fk_montadora' => '66', 'descricao' => 'ES 350'],
            ['fk_montadora' => '66', 'descricao' => 'GS'],
            ['fk_montadora' => '66', 'descricao' => 'GS 350'],
            ['fk_montadora' => '66', 'descricao' => 'IS 250'],
            ['fk_montadora' => '66', 'descricao' => 'IS250 F-SPORT'],
            ['fk_montadora' => '66', 'descricao' => 'IS300'],
            ['fk_montadora' => '66', 'descricao' => 'LS'],
            ['fk_montadora' => '66', 'descricao' => 'LS 460 L'],
            ['fk_montadora' => '66', 'descricao' => 'NX 200T'],
            ['fk_montadora' => '66', 'descricao' => 'RX 330'],
            ['fk_montadora' => '66', 'descricao' => 'RX 350'],
            ['fk_montadora' => '66', 'descricao' => 'RX350 F-SPORT'],
            ['fk_montadora' => '66', 'descricao' => 'SC 400'],
            ['fk_montadora' => '67', 'descricao' => '320'],
            ['fk_montadora' => '67', 'descricao' => '530'],
            ['fk_montadora' => '67', 'descricao' => '620'],
            ['fk_montadora' => '67', 'descricao' => 'FOISON'],
            ['fk_montadora' => '67', 'descricao' => 'X60'],
            ['fk_montadora' => '68', 'descricao' => 'CONTINENTAL'],
            ['fk_montadora' => '68', 'descricao' => 'LS'],
            ['fk_montadora' => '68', 'descricao' => 'MARK VIII'],
            ['fk_montadora' => '68', 'descricao' => 'NAVIGATOR'],
            ['fk_montadora' => '68', 'descricao' => 'TOWN CAR'],
            ['fk_montadora' => '69', 'descricao' => 'H1'],
            ['fk_montadora' => '70', 'descricao' => 'ELISE'],
            ['fk_montadora' => '70', 'descricao' => 'EXIGE'],
            ['fk_montadora' => '71', 'descricao' => 'PICKUP'],
            ['fk_montadora' => '71', 'descricao' => 'SCORPIO'],
            ['fk_montadora' => '71', 'descricao' => 'SUV'],
            ['fk_montadora' => '72', 'descricao' => 'VOLARE'],
            ['fk_montadora' => '73', 'descricao' => '3200'],
            ['fk_montadora' => '73', 'descricao' => 'COUPÉ'],
            ['fk_montadora' => '73', 'descricao' => 'GHIBLI'],
            ['fk_montadora' => '73', 'descricao' => 'GRAN TURISMO'],
            ['fk_montadora' => '73', 'descricao' => 'GRANCABRIO'],
            ['fk_montadora' => '73', 'descricao' => 'GRANSPORT'],
            ['fk_montadora' => '73', 'descricao' => 'QUATTROPORTE'],
            ['fk_montadora' => '73', 'descricao' => 'SPYDER'],
            ['fk_montadora' => '74', 'descricao' => 'PICK-UP'],
            ['fk_montadora' => '75', 'descricao' => '626'],
            ['fk_montadora' => '75', 'descricao' => 'MPV'],
            ['fk_montadora' => '75', 'descricao' => 'MX-3'],
            ['fk_montadora' => '75', 'descricao' => 'MX-5'],
            ['fk_montadora' => '76', 'descricao' => 'MP4-12C'],
            ['fk_montadora' => '77', 'descricao' => '170 S'],
            ['fk_montadora' => '77', 'descricao' => '180 D'],
            ['fk_montadora' => '77', 'descricao' => '190 E'],
            ['fk_montadora' => '77', 'descricao' => '220'],
            ['fk_montadora' => '77', 'descricao' => '220 S'],
            ['fk_montadora' => '77', 'descricao' => '230 E'],
            ['fk_montadora' => '77', 'descricao' => '250'],
            ['fk_montadora' => '77', 'descricao' => '250 S'],
            ['fk_montadora' => '77', 'descricao' => '260 E'],
            ['fk_montadora' => '77', 'descricao' => '280 CE'],
            ['fk_montadora' => '77', 'descricao' => '280 E'],
            ['fk_montadora' => '77', 'descricao' => '280 S'],
            ['fk_montadora' => '77', 'descricao' => '280 SE'],
            ['fk_montadora' => '77', 'descricao' => '280 SL'],
            ['fk_montadora' => '77', 'descricao' => '300 CE'],
            ['fk_montadora' => '77', 'descricao' => '300 E'],
            ['fk_montadora' => '77', 'descricao' => '300 SD'],
            ['fk_montadora' => '77', 'descricao' => '300 SEL'],
            ['fk_montadora' => '77', 'descricao' => '300 SL'],
            ['fk_montadora' => '77', 'descricao' => '300 TD'],
            ['fk_montadora' => '77', 'descricao' => '300 TE'],
            ['fk_montadora' => '77', 'descricao' => '320 CE'],
            ['fk_montadora' => '77', 'descricao' => '320 E'],
            ['fk_montadora' => '77', 'descricao' => '320 SL'],
            ['fk_montadora' => '77', 'descricao' => '350 SL'],
            ['fk_montadora' => '77', 'descricao' => '450 SL'],
            ['fk_montadora' => '77', 'descricao' => '450 SLC'],
            ['fk_montadora' => '77', 'descricao' => '500 SE'],
            ['fk_montadora' => '77', 'descricao' => '500 SEL'],
            ['fk_montadora' => '77', 'descricao' => '500 SL'],
            ['fk_montadora' => '77', 'descricao' => '560 SEL'],
            ['fk_montadora' => '77', 'descricao' => 'A 190'],
            ['fk_montadora' => '77', 'descricao' => 'A 200'],
            ['fk_montadora' => '77', 'descricao' => 'A 250'],
            ['fk_montadora' => '77', 'descricao' => 'A 45 AMG'],
            ['fk_montadora' => '77', 'descricao' => 'AMG GT'],
            ['fk_montadora' => '77', 'descricao' => 'B 170'],
            ['fk_montadora' => '77', 'descricao' => 'B 180'],
            ['fk_montadora' => '77', 'descricao' => 'B 200'],
            ['fk_montadora' => '77', 'descricao' => 'C 180'],
            ['fk_montadora' => '77', 'descricao' => 'C 180 K'],
            ['fk_montadora' => '77', 'descricao' => 'C 200'],
            ['fk_montadora' => '77', 'descricao' => 'C 200 K'],
            ['fk_montadora' => '77', 'descricao' => 'C 220'],
            ['fk_montadora' => '77', 'descricao' => 'C 230'],
            ['fk_montadora' => '77', 'descricao' => 'C 230 K'],
            ['fk_montadora' => '77', 'descricao' => 'C 240'],
            ['fk_montadora' => '77', 'descricao' => 'C 250'],
            ['fk_montadora' => '77', 'descricao' => 'C 280'],
            ['fk_montadora' => '77', 'descricao' => 'C 300'],
            ['fk_montadora' => '77', 'descricao' => 'C 320'],
            ['fk_montadora' => '77', 'descricao' => 'C 32K AMG'],
            ['fk_montadora' => '77', 'descricao' => 'C 350'],
            ['fk_montadora' => '77', 'descricao' => 'C 36 AMG'],
            ['fk_montadora' => '77', 'descricao' => 'C 450'],
            ['fk_montadora' => '77', 'descricao' => 'C 55 AMG'],
            ['fk_montadora' => '77', 'descricao' => 'C 63 AMG'],
            ['fk_montadora' => '77', 'descricao' => 'CL 500'],
            ['fk_montadora' => '77', 'descricao' => 'CL 55 AMG'],
            ['fk_montadora' => '77', 'descricao' => 'CL 600'],
            ['fk_montadora' => '77', 'descricao' => 'CL 63 AMG'],
            ['fk_montadora' => '77', 'descricao' => 'CL 65 AMG'],
            ['fk_montadora' => '77', 'descricao' => 'CLA 200'],
            ['fk_montadora' => '77', 'descricao' => 'CLA 250'],
            ['fk_montadora' => '77', 'descricao' => 'CLA 45 AMG'],
            ['fk_montadora' => '77', 'descricao' => 'CLASSE A'],
            ['fk_montadora' => '77', 'descricao' => 'CLC 200'],
            ['fk_montadora' => '77', 'descricao' => 'CLC 200 K'],
            ['fk_montadora' => '77', 'descricao' => 'CLK 230'],
            ['fk_montadora' => '77', 'descricao' => 'CLK 320'],
            ['fk_montadora' => '77', 'descricao' => 'CLK 350'],
            ['fk_montadora' => '77', 'descricao' => 'CLK 430'],
            ['fk_montadora' => '77', 'descricao' => 'CLK 500'],
            ['fk_montadora' => '77', 'descricao' => 'CLS 350'],
            ['fk_montadora' => '77', 'descricao' => 'CLS 400'],
            ['fk_montadora' => '77', 'descricao' => 'CLS 500'],
            ['fk_montadora' => '77', 'descricao' => 'CLS 63 AMG'],
            ['fk_montadora' => '77', 'descricao' => 'E 220'],
            ['fk_montadora' => '77', 'descricao' => 'E 240'],
            ['fk_montadora' => '77', 'descricao' => 'E 250'],
            ['fk_montadora' => '77', 'descricao' => 'E 320'],
            ['fk_montadora' => '77', 'descricao' => 'E 350'],
            ['fk_montadora' => '77', 'descricao' => 'E 400'],
            ['fk_montadora' => '77', 'descricao' => 'E 420'],
            ['fk_montadora' => '77', 'descricao' => 'E 430'],
            ['fk_montadora' => '77', 'descricao' => 'E 500'],
            ['fk_montadora' => '77', 'descricao' => 'E 55 AMG'],
            ['fk_montadora' => '77', 'descricao' => 'E 63 AMG'],
            ['fk_montadora' => '77', 'descricao' => 'G 500'],
            ['fk_montadora' => '77', 'descricao' => 'G 55 AMG'],
            ['fk_montadora' => '77', 'descricao' => 'G 63 AMG'],
            ['fk_montadora' => '77', 'descricao' => 'GL 350'],
            ['fk_montadora' => '77', 'descricao' => 'GL 500'],
            ['fk_montadora' => '77', 'descricao' => 'GL 63 AMG'],
            ['fk_montadora' => '77', 'descricao' => 'GLA 200'],
            ['fk_montadora' => '77', 'descricao' => 'GLA 250'],
            ['fk_montadora' => '77', 'descricao' => 'GLA 45 AMG'],
            ['fk_montadora' => '77', 'descricao' => 'GLK 220'],
            ['fk_montadora' => '77', 'descricao' => 'GLK 280'],
            ['fk_montadora' => '77', 'descricao' => 'GLK 300'],
            ['fk_montadora' => '77', 'descricao' => 'MICROÔNIBUS'],
            ['fk_montadora' => '77', 'descricao' => 'ML 320'],
            ['fk_montadora' => '77', 'descricao' => 'ML 350'],
            ['fk_montadora' => '77', 'descricao' => 'ML 430'],
            ['fk_montadora' => '77', 'descricao' => 'ML 500'],
            ['fk_montadora' => '77', 'descricao' => 'ML 63 AMG'],
            ['fk_montadora' => '77', 'descricao' => 'R 500'],
            ['fk_montadora' => '77', 'descricao' => 'S 320'],
            ['fk_montadora' => '77', 'descricao' => 'S 350'],
            ['fk_montadora' => '77', 'descricao' => 'S 400'],
            ['fk_montadora' => '77', 'descricao' => 'S 500'],
            ['fk_montadora' => '77', 'descricao' => 'S 500 L'],
            ['fk_montadora' => '77', 'descricao' => 'S 600'],
            ['fk_montadora' => '77', 'descricao' => 'S 63 AMG'],
            ['fk_montadora' => '77', 'descricao' => 'S 65 AMG'],
            ['fk_montadora' => '77', 'descricao' => 'SL 320'],
            ['fk_montadora' => '77', 'descricao' => 'SL 350'],
            ['fk_montadora' => '77', 'descricao' => 'SL 400'],
            ['fk_montadora' => '77', 'descricao' => 'SL 500'],
            ['fk_montadora' => '77', 'descricao' => 'SL 55 AMG'],
            ['fk_montadora' => '77', 'descricao' => 'SL 600'],
            ['fk_montadora' => '77', 'descricao' => 'SL 63 AMG'],
            ['fk_montadora' => '77', 'descricao' => 'SL 65 AMG'],
            ['fk_montadora' => '77', 'descricao' => 'SLK 200'],
            ['fk_montadora' => '77', 'descricao' => 'SLK 230'],
            ['fk_montadora' => '77', 'descricao' => 'SLK 250'],
            ['fk_montadora' => '77', 'descricao' => 'SLK 300'],
            ['fk_montadora' => '77', 'descricao' => 'SLK 320'],
            ['fk_montadora' => '77', 'descricao' => 'SLK 350'],
            ['fk_montadora' => '77', 'descricao' => 'SLK 55 AMG'],
            ['fk_montadora' => '77', 'descricao' => 'SLS AMG'],
            ['fk_montadora' => '77', 'descricao' => 'SPRINTER'],
            ['fk_montadora' => '77', 'descricao' => 'VITO'],
            ['fk_montadora' => '78', 'descricao' => 'COUGAR'],
            ['fk_montadora' => '78', 'descricao' => 'GRAND MARQUIS'],
            ['fk_montadora' => '78', 'descricao' => 'MONTEREY'],
            ['fk_montadora' => '79', 'descricao' => 'MG 550'],
            ['fk_montadora' => '79', 'descricao' => 'MG 6'],
            ['fk_montadora' => '79', 'descricao' => 'MGB'],
            ['fk_montadora' => '79', 'descricao' => 'MGF'],
            ['fk_montadora' => '79', 'descricao' => 'TD'],
            ['fk_montadora' => '80', 'descricao' => 'COOPER'],
            ['fk_montadora' => '80', 'descricao' => 'COUNTRYMAN'],
            ['fk_montadora' => '80', 'descricao' => 'JOHN COOPER WORKS'],
            ['fk_montadora' => '80', 'descricao' => 'MORRIS'],
            ['fk_montadora' => '80', 'descricao' => 'ONE'],
            ['fk_montadora' => '80', 'descricao' => 'PACEMAN'],
            ['fk_montadora' => '80', 'descricao' => 'ROADSTER'],
            ['fk_montadora' => '81', 'descricao' => '3000 GT'],
            ['fk_montadora' => '81', 'descricao' => 'AIRTREK'],
            ['fk_montadora' => '81', 'descricao' => 'ASX'],
            ['fk_montadora' => '81', 'descricao' => 'COLT'],
            ['fk_montadora' => '81', 'descricao' => 'ECLIPSE'],
            ['fk_montadora' => '81', 'descricao' => 'GALANT'],
            ['fk_montadora' => '81', 'descricao' => 'GRANDIS'],
            ['fk_montadora' => '81', 'descricao' => 'L200'],
            ['fk_montadora' => '81', 'descricao' => 'L200 OUTDOOR'],
            ['fk_montadora' => '81', 'descricao' => 'L200 SAVANA'],
            ['fk_montadora' => '81', 'descricao' => 'L200 TRITON'],
            ['fk_montadora' => '81', 'descricao' => 'LANCER'],
            ['fk_montadora' => '81', 'descricao' => 'OUTLANDER'],
            ['fk_montadora' => '81', 'descricao' => 'PAJERO'],
            ['fk_montadora' => '81', 'descricao' => 'PAJERO DAKAR'],
            ['fk_montadora' => '81', 'descricao' => 'PAJERO FULL'],
            ['fk_montadora' => '81', 'descricao' => 'PAJERO IO'],
            ['fk_montadora' => '81', 'descricao' => 'PAJERO SPORT'],
            ['fk_montadora' => '81', 'descricao' => 'PAJERO TR4'],
            ['fk_montadora' => '81', 'descricao' => 'SPACE WAGON'],
            ['fk_montadora' => '81', 'descricao' => '3000 GT'],
            ['fk_montadora' => '81', 'descricao' => 'AIRTREK'],
            ['fk_montadora' => '81', 'descricao' => 'ASX'],
            ['fk_montadora' => '81', 'descricao' => 'COLT'],
            ['fk_montadora' => '81', 'descricao' => 'ECLIPSE'],
            ['fk_montadora' => '81', 'descricao' => 'GALANT'],
            ['fk_montadora' => '81', 'descricao' => 'GRANDIS'],
            ['fk_montadora' => '81', 'descricao' => 'L200'],
            ['fk_montadora' => '81', 'descricao' => 'L200 OUTDOOR'],
            ['fk_montadora' => '81', 'descricao' => 'L200 SAVANA'],
            ['fk_montadora' => '81', 'descricao' => 'L200 TRITON'],
            ['fk_montadora' => '81', 'descricao' => 'LANCER'],
            ['fk_montadora' => '81', 'descricao' => 'OUTLANDER'],
            ['fk_montadora' => '81', 'descricao' => 'PAJERO'],
            ['fk_montadora' => '81', 'descricao' => 'PAJERO DAKAR'],
            ['fk_montadora' => '81', 'descricao' => 'PAJERO FULL'],
            ['fk_montadora' => '81', 'descricao' => 'PAJERO IO'],
            ['fk_montadora' => '81', 'descricao' => 'PAJERO SPORT'],
            ['fk_montadora' => '81', 'descricao' => 'PAJERO TR4'],
            ['fk_montadora' => '81', 'descricao' => 'SPACE WAGON'],
            ['fk_montadora' => '82', 'descricao' => 'BG'],
            ['fk_montadora' => '83', 'descricao' => '1300'],
            ['fk_montadora' => '83', 'descricao' => 'MINI'],
            ['fk_montadora' => '84', 'descricao' => 'CLASSICO'],
            ['fk_montadora' => '85', 'descricao' => '350Z'],
            ['fk_montadora' => '85', 'descricao' => '370Z'],
            ['fk_montadora' => '85', 'descricao' => 'ALTIMA'],
            ['fk_montadora' => '85', 'descricao' => 'ARMADA'],
            ['fk_montadora' => '85', 'descricao' => 'D 21'],
            ['fk_montadora' => '85', 'descricao' => 'FRONTIER'],
            ['fk_montadora' => '85', 'descricao' => 'GRAND LIVINA'],
            ['fk_montadora' => '85', 'descricao' => 'GT-R'],
            ['fk_montadora' => '85', 'descricao' => 'JUKE'],
            ['fk_montadora' => '85', 'descricao' => 'LIVINA'],
            ['fk_montadora' => '85', 'descricao' => 'MARCH'],
            ['fk_montadora' => '85', 'descricao' => 'MAXIMA'],
            ['fk_montadora' => '85', 'descricao' => 'MURANO'],
            ['fk_montadora' => '85', 'descricao' => 'PATHFINDER'],
            ['fk_montadora' => '85', 'descricao' => 'QUEST'],
            ['fk_montadora' => '85', 'descricao' => 'SENTRA'],
            ['fk_montadora' => '85', 'descricao' => 'TERRANO'],
            ['fk_montadora' => '85', 'descricao' => 'TIIDA'],
            ['fk_montadora' => '85', 'descricao' => 'VERSA'],
            ['fk_montadora' => '85', 'descricao' => 'XTERRA'],
            ['fk_montadora' => '85', 'descricao' => 'X-TRAIL'],
            ['fk_montadora' => '86', 'descricao' => 'CUTLASS SUPREME'],
            ['fk_montadora' => '86', 'descricao' => 'TORONADO'],
            ['fk_montadora' => '87', 'descricao' => 'GT'],
            ['fk_montadora' => '87', 'descricao' => 'KADETT'],
            ['fk_montadora' => '88', 'descricao' => 'SIX'],
            ['fk_montadora' => '89', 'descricao' => 'NICK'],
            ['fk_montadora' => '90', 'descricao' => '106'],
            ['fk_montadora' => '90', 'descricao' => '2008'],
            ['fk_montadora' => '90', 'descricao' => '206'],
            ['fk_montadora' => '90', 'descricao' => '207'],
            ['fk_montadora' => '90', 'descricao' => '208'],
            ['fk_montadora' => '90', 'descricao' => '3008'],
            ['fk_montadora' => '90', 'descricao' => '306'],
            ['fk_montadora' => '90', 'descricao' => '307'],
            ['fk_montadora' => '90', 'descricao' => '308'],
            ['fk_montadora' => '90', 'descricao' => '308cc'],
            ['fk_montadora' => '90', 'descricao' => '406'],
            ['fk_montadora' => '90', 'descricao' => '407'],
            ['fk_montadora' => '90', 'descricao' => '408'],
            ['fk_montadora' => '90', 'descricao' => '504'],
            ['fk_montadora' => '90', 'descricao' => '508'],
            ['fk_montadora' => '90', 'descricao' => '605'],
            ['fk_montadora' => '90', 'descricao' => '607'],
            ['fk_montadora' => '90', 'descricao' => '807'],
            ['fk_montadora' => '90', 'descricao' => 'BOXER'],
            ['fk_montadora' => '90', 'descricao' => 'HOGGAR'],
            ['fk_montadora' => '90', 'descricao' => 'PARTNER'],
            ['fk_montadora' => '90', 'descricao' => 'RCZ'],
            ['fk_montadora' => '90', 'descricao' => '106'],
            ['fk_montadora' => '90', 'descricao' => '2008'],
            ['fk_montadora' => '90', 'descricao' => '206'],
            ['fk_montadora' => '90', 'descricao' => '207'],
            ['fk_montadora' => '90', 'descricao' => '208'],
            ['fk_montadora' => '90', 'descricao' => '3008'],
            ['fk_montadora' => '90', 'descricao' => '306'],
            ['fk_montadora' => '90', 'descricao' => '307'],
            ['fk_montadora' => '90', 'descricao' => '308'],
            ['fk_montadora' => '90', 'descricao' => '308cc'],
            ['fk_montadora' => '90', 'descricao' => '406'],
            ['fk_montadora' => '90', 'descricao' => '407'],
            ['fk_montadora' => '90', 'descricao' => '408'],
            ['fk_montadora' => '90', 'descricao' => '504'],
            ['fk_montadora' => '90', 'descricao' => '508'],
            ['fk_montadora' => '90', 'descricao' => '605'],
            ['fk_montadora' => '90', 'descricao' => '607'],
            ['fk_montadora' => '90', 'descricao' => '807'],
            ['fk_montadora' => '90', 'descricao' => 'BOXER'],
            ['fk_montadora' => '90', 'descricao' => 'HOGGAR'],
            ['fk_montadora' => '90', 'descricao' => 'PARTNER'],
            ['fk_montadora' => '90', 'descricao' => 'RCZ'],
            ['fk_montadora' => '91', 'descricao' => 'ACCLAIM'],
            ['fk_montadora' => '91', 'descricao' => 'BARRACUDA'],
            ['fk_montadora' => '92', 'descricao' => 'FIREBIRD'],
            ['fk_montadora' => '92', 'descricao' => 'FORMULA 400'],
            ['fk_montadora' => '92', 'descricao' => 'SOLSTICE'],
            ['fk_montadora' => '93', 'descricao' => '356'],
            ['fk_montadora' => '93', 'descricao' => '911'],
            ['fk_montadora' => '93', 'descricao' => '914'],
            ['fk_montadora' => '93', 'descricao' => '928'],
            ['fk_montadora' => '93', 'descricao' => 'BOXSTER'],
            ['fk_montadora' => '93', 'descricao' => 'CAYENNE'],
            ['fk_montadora' => '93', 'descricao' => 'CAYMAN'],
            ['fk_montadora' => '93', 'descricao' => 'CAYMAN R'],
            ['fk_montadora' => '93', 'descricao' => 'CAYMAN S'],
            ['fk_montadora' => '93', 'descricao' => 'MACAN'],
            ['fk_montadora' => '93', 'descricao' => 'PANAMERA'],
            ['fk_montadora' => '93', 'descricao' => 'SPYDER 500'],
            ['fk_montadora' => '93', 'descricao' => 'SPYDER 550'],
            ['fk_montadora' => '94', 'descricao' => 'AMV'],
            ['fk_montadora' => '94', 'descricao' => 'GT'],
            ['fk_montadora' => '94', 'descricao' => 'GTB/S2'],
            ['fk_montadora' => '94', 'descricao' => 'GTC'],
            ['fk_montadora' => '94', 'descricao' => 'GTE'],
            ['fk_montadora' => '94', 'descricao' => 'GTS'],
            ['fk_montadora' => '95', 'descricao' => 'LINK'],
            ['fk_montadora' => '95', 'descricao' => 'PICK-UP'],
            ['fk_montadora' => '95', 'descricao' => 'VAN'],
            ['fk_montadora' => '96', 'descricao' => '19'],
            ['fk_montadora' => '96', 'descricao' => 'CLIO'],
            ['fk_montadora' => '96', 'descricao' => 'DAUPHINE'],
            ['fk_montadora' => '96', 'descricao' => 'DUSTER'],
            ['fk_montadora' => '96', 'descricao' => 'DUSTER OROCH'],
            ['fk_montadora' => '96', 'descricao' => 'EXPRESS'],
            ['fk_montadora' => '96', 'descricao' => 'FLUENCE'],
            ['fk_montadora' => '96', 'descricao' => 'GORDINI'],
            ['fk_montadora' => '96', 'descricao' => 'GRAND SCÉNIC'],
            ['fk_montadora' => '96', 'descricao' => 'KANGOO'],
            ['fk_montadora' => '96', 'descricao' => 'LAGUNA'],
            ['fk_montadora' => '96', 'descricao' => 'LOGAN'],
            ['fk_montadora' => '96', 'descricao' => 'MASTER'],
            ['fk_montadora' => '96', 'descricao' => 'MÉGANE'],
            ['fk_montadora' => '96', 'descricao' => 'SANDERO'],
            ['fk_montadora' => '96', 'descricao' => 'SCÉNIC'],
            ['fk_montadora' => '96', 'descricao' => 'SYMBOL'],
            ['fk_montadora' => '96', 'descricao' => 'TRAFIC'],
            ['fk_montadora' => '96', 'descricao' => 'TWINGO'],
            ['fk_montadora' => '96', 'descricao' => '19'],
            ['fk_montadora' => '96', 'descricao' => 'CLIO'],
            ['fk_montadora' => '96', 'descricao' => 'DAUPHINE'],
            ['fk_montadora' => '96', 'descricao' => 'DUSTER'],
            ['fk_montadora' => '96', 'descricao' => 'DUSTER OROCH'],
            ['fk_montadora' => '96', 'descricao' => 'EXPRESS'],
            ['fk_montadora' => '96', 'descricao' => 'FLUENCE'],
            ['fk_montadora' => '96', 'descricao' => 'GORDINI'],
            ['fk_montadora' => '96', 'descricao' => 'GRAND SCÉNIC'],
            ['fk_montadora' => '96', 'descricao' => 'KANGOO'],
            ['fk_montadora' => '96', 'descricao' => 'LAGUNA'],
            ['fk_montadora' => '96', 'descricao' => 'LOGAN'],
            ['fk_montadora' => '96', 'descricao' => 'MASTER'],
            ['fk_montadora' => '96', 'descricao' => 'MÉGANE'],
            ['fk_montadora' => '96', 'descricao' => 'SANDERO'],
            ['fk_montadora' => '96', 'descricao' => 'SCÉNIC'],
            ['fk_montadora' => '96', 'descricao' => 'SYMBOL'],
            ['fk_montadora' => '96', 'descricao' => 'TRAFIC'],
            ['fk_montadora' => '96', 'descricao' => 'TWINGO'],
            ['fk_montadora' => '97', 'descricao' => 'STANDARD'],
            ['fk_montadora' => '98', 'descricao' => 'CORNICHE'],
            ['fk_montadora' => '98', 'descricao' => 'GHOST'],
            ['fk_montadora' => '98', 'descricao' => 'PHANTOM'],
            ['fk_montadora' => '98', 'descricao' => 'SILVER SHADOW'],
            ['fk_montadora' => '98', 'descricao' => 'SILVER SHADOW II'],
            ['fk_montadora' => '98', 'descricao' => 'SILVER SPUR'],
            ['fk_montadora' => '98', 'descricao' => 'SILVER WRAITH II'],
            ['fk_montadora' => '98', 'descricao' => 'WRAITH'],
            ['fk_montadora' => '99', 'descricao' => 'ROMI-ISETTA'],
            ['fk_montadora' => '100', 'descricao' => '9000'],
            ['fk_montadora' => '101', 'descricao' => 'SM 4.1'],
            ['fk_montadora' => '102', 'descricao' => 'SL-2'],
            ['fk_montadora' => '103', 'descricao' => 'CORDOBA'],
            ['fk_montadora' => '103', 'descricao' => 'IBIZA'],
            ['fk_montadora' => '103', 'descricao' => 'INCA'],
            ['fk_montadora' => '104', 'descricao' => 'S'],
            ['fk_montadora' => '105', 'descricao' => 'COBRA'],
            ['fk_montadora' => '105', 'descricao' => 'GT 500'],
            ['fk_montadora' => '106', 'descricao' => 'A7'],
            ['fk_montadora' => '106', 'descricao' => 'A9'],
            ['fk_montadora' => '106', 'descricao' => 'A9 CARGO'],
            ['fk_montadora' => '106', 'descricao' => 'SY1020'],
            ['fk_montadora' => '106', 'descricao' => 'T20'],
            ['fk_montadora' => '106', 'descricao' => 'T20 BAÚ'],
            ['fk_montadora' => '106', 'descricao' => 'T22'],
            ['fk_montadora' => '106', 'descricao' => 'X30'],
            ['fk_montadora' => '107', 'descricao' => 'FORTWO'],
            ['fk_montadora' => '108', 'descricao' => 'ACTYON'],
            ['fk_montadora' => '108', 'descricao' => 'ACTYON SPORTS'],
            ['fk_montadora' => '108', 'descricao' => 'KORANDO'],
            ['fk_montadora' => '108', 'descricao' => 'KYRON'],
            ['fk_montadora' => '108', 'descricao' => 'REXTON'],
            ['fk_montadora' => '108', 'descricao' => 'REXTON II'],
            ['fk_montadora' => '109', 'descricao' => 'VANGUARD'],
            ['fk_montadora' => '110', 'descricao' => 'STUDEBAKER'],
            ['fk_montadora' => '111', 'descricao' => 'FORESTER'],
            ['fk_montadora' => '111', 'descricao' => 'IMPREZA'],
            ['fk_montadora' => '111', 'descricao' => 'LEGACY'],
            ['fk_montadora' => '111', 'descricao' => 'OUTBACK'],
            ['fk_montadora' => '111', 'descricao' => 'SVX'],
            ['fk_montadora' => '111', 'descricao' => 'TRIBECA'],
            ['fk_montadora' => '111', 'descricao' => 'VIVIO'],
            ['fk_montadora' => '111', 'descricao' => 'XV'],
            ['fk_montadora' => '112', 'descricao' => 'GRAND VITARA'],
            ['fk_montadora' => '112', 'descricao' => 'IGNIS'],
            ['fk_montadora' => '112', 'descricao' => 'JIMNY'],
            ['fk_montadora' => '112', 'descricao' => 'SAMURAI'],
            ['fk_montadora' => '112', 'descricao' => 'S-CROSS'],
            ['fk_montadora' => '112', 'descricao' => 'SIDEKICK'],
            ['fk_montadora' => '112', 'descricao' => 'SWIFT'],
            ['fk_montadora' => '112', 'descricao' => 'SX4'],
            ['fk_montadora' => '112', 'descricao' => 'VITARA'],
            ['fk_montadora' => '113', 'descricao' => 'STARK'],
            ['fk_montadora' => '114', 'descricao' => 'MODEL S'],
            ['fk_montadora' => '115', 'descricao' => 'AVALON'],
            ['fk_montadora' => '115', 'descricao' => 'BANDEIRANTE'],
            ['fk_montadora' => '115', 'descricao' => 'CAMRY'],
            ['fk_montadora' => '115', 'descricao' => 'COROLLA'],
            ['fk_montadora' => '115', 'descricao' => 'CORONA'],
            ['fk_montadora' => '115', 'descricao' => 'ETIOS'],
            ['fk_montadora' => '115', 'descricao' => 'ETIOS CROSS'],
            ['fk_montadora' => '115', 'descricao' => 'FIELDER'],
            ['fk_montadora' => '115', 'descricao' => 'FJ CRUISER'],
            ['fk_montadora' => '115', 'descricao' => 'HILUX'],
            ['fk_montadora' => '115', 'descricao' => 'HILUX SW4'],
            ['fk_montadora' => '115', 'descricao' => 'LAND CRUISER PRADO'],
            ['fk_montadora' => '115', 'descricao' => 'MR-2'],
            ['fk_montadora' => '115', 'descricao' => 'PASEO'],
            ['fk_montadora' => '115', 'descricao' => 'PREVIA'],
            ['fk_montadora' => '115', 'descricao' => 'PRIUS'],
            ['fk_montadora' => '115', 'descricao' => 'RAV4'],
            ['fk_montadora' => '115', 'descricao' => 'SIENNA'],
            ['fk_montadora' => '115', 'descricao' => 'TUNDRA'],
            ['fk_montadora' => '115', 'descricao' => 'VENZA'],
            ['fk_montadora' => '115', 'descricao' => 'AVALON'],
            ['fk_montadora' => '115', 'descricao' => 'BANDEIRANTE'],
            ['fk_montadora' => '115', 'descricao' => 'CAMRY'],
            ['fk_montadora' => '115', 'descricao' => 'COROLLA'],
            ['fk_montadora' => '115', 'descricao' => 'CORONA'],
            ['fk_montadora' => '115', 'descricao' => 'ETIOS'],
            ['fk_montadora' => '115', 'descricao' => 'ETIOS CROSS'],
            ['fk_montadora' => '115', 'descricao' => 'FIELDER'],
            ['fk_montadora' => '115', 'descricao' => 'FJ CRUISER'],
            ['fk_montadora' => '115', 'descricao' => 'HILUX'],
            ['fk_montadora' => '115', 'descricao' => 'HILUX SW4'],
            ['fk_montadora' => '115', 'descricao' => 'LAND CRUISER PRADO'],
            ['fk_montadora' => '115', 'descricao' => 'MR-2'],
            ['fk_montadora' => '115', 'descricao' => 'PASEO'],
            ['fk_montadora' => '115', 'descricao' => 'PREVIA'],
            ['fk_montadora' => '115', 'descricao' => 'PRIUS'],
            ['fk_montadora' => '115', 'descricao' => 'RAV4'],
            ['fk_montadora' => '115', 'descricao' => 'SIENNA'],
            ['fk_montadora' => '115', 'descricao' => 'TUNDRA'],
            ['fk_montadora' => '115', 'descricao' => 'VENZA'],
            ['fk_montadora' => '116', 'descricao' => 'SPITFIRE'],
            ['fk_montadora' => '117', 'descricao' => 'RF'],
            ['fk_montadora' => '117', 'descricao' => 'T4'],
            ['fk_montadora' => '117', 'descricao' => 'T5'],
            ['fk_montadora' => '118', 'descricao' => '1300'],
            ['fk_montadora' => '118', 'descricao' => '1500'],
            ['fk_montadora' => '118', 'descricao' => '1600'],
            ['fk_montadora' => '118', 'descricao' => 'AMAROK'],
            ['fk_montadora' => '118', 'descricao' => 'APOLLO'],
            ['fk_montadora' => '118', 'descricao' => 'BORA'],
            ['fk_montadora' => '118', 'descricao' => 'BRASILIA'],
            ['fk_montadora' => '118', 'descricao' => 'BUGGY'],
            ['fk_montadora' => '118', 'descricao' => 'CROSS UP'],
            ['fk_montadora' => '118', 'descricao' => 'CROSSFOX'],
            ['fk_montadora' => '118', 'descricao' => 'EOS'],
            ['fk_montadora' => '118', 'descricao' => 'EUROVAN'],
            ['fk_montadora' => '118', 'descricao' => 'FOX'],
            ['fk_montadora' => '118', 'descricao' => 'FUSCA'],
            ['fk_montadora' => '118', 'descricao' => 'GOL'],
            ['fk_montadora' => '118', 'descricao' => 'GOLF'],
            ['fk_montadora' => '118', 'descricao' => 'JETTA'],
            ['fk_montadora' => '118', 'descricao' => 'KARMANN-GHIA'],
            ['fk_montadora' => '118', 'descricao' => 'KOMBI'],
            ['fk_montadora' => '118', 'descricao' => 'LOGUS'],
            ['fk_montadora' => '118', 'descricao' => 'NEW BEETLE'],
            ['fk_montadora' => '118', 'descricao' => 'PARATI'],
            ['fk_montadora' => '118', 'descricao' => 'PASSAT'],
            ['fk_montadora' => '118', 'descricao' => 'PASSAT VARIANT'],
            ['fk_montadora' => '118', 'descricao' => 'POINTER'],
            ['fk_montadora' => '118', 'descricao' => 'POLO'],
            ['fk_montadora' => '118', 'descricao' => 'POLO SEDAN'],
            ['fk_montadora' => '118', 'descricao' => 'QUANTUM'],
            ['fk_montadora' => '118', 'descricao' => 'SANTANA'],
            ['fk_montadora' => '118', 'descricao' => 'SAVEIRO'],
            ['fk_montadora' => '118', 'descricao' => 'SCIROCCO'],
            ['fk_montadora' => '118', 'descricao' => 'SP2'],
            ['fk_montadora' => '118', 'descricao' => 'SPACE CROSS'],
            ['fk_montadora' => '118', 'descricao' => 'SPACEFOX'],
            ['fk_montadora' => '118', 'descricao' => 'TIGUAN'],
            ['fk_montadora' => '118', 'descricao' => 'TL'],
            ['fk_montadora' => '118', 'descricao' => 'TOUAREG'],
            ['fk_montadora' => '118', 'descricao' => 'UP'],
            ['fk_montadora' => '118', 'descricao' => 'VAN'],
            ['fk_montadora' => '118', 'descricao' => 'VARIANT'],
            ['fk_montadora' => '118', 'descricao' => 'VARIANT II'],
            ['fk_montadora' => '118', 'descricao' => 'VOYAGE'],
            ['fk_montadora' => '118', 'descricao' => '1300'],
            ['fk_montadora' => '118', 'descricao' => '1500'],
            ['fk_montadora' => '118', 'descricao' => '1600'],
            ['fk_montadora' => '118', 'descricao' => 'AMAROK'],
            ['fk_montadora' => '118', 'descricao' => 'APOLLO'],
            ['fk_montadora' => '118', 'descricao' => 'BORA'],
            ['fk_montadora' => '118', 'descricao' => 'BRASILIA'],
            ['fk_montadora' => '118', 'descricao' => 'BUGGY'],
            ['fk_montadora' => '118', 'descricao' => 'CROSS UP'],
            ['fk_montadora' => '118', 'descricao' => 'CROSSFOX'],
            ['fk_montadora' => '118', 'descricao' => 'EOS'],
            ['fk_montadora' => '118', 'descricao' => 'EUROVAN'],
            ['fk_montadora' => '118', 'descricao' => 'FOX'],
            ['fk_montadora' => '118', 'descricao' => 'FUSCA'],
            ['fk_montadora' => '118', 'descricao' => 'GOL'],
            ['fk_montadora' => '118', 'descricao' => 'GOLF'],
            ['fk_montadora' => '118', 'descricao' => 'JETTA'],
            ['fk_montadora' => '118', 'descricao' => 'KARMANN-GHIA'],
            ['fk_montadora' => '118', 'descricao' => 'KOMBI'],
            ['fk_montadora' => '118', 'descricao' => 'LOGUS'],
            ['fk_montadora' => '118', 'descricao' => 'NEW BEETLE'],
            ['fk_montadora' => '118', 'descricao' => 'PARATI'],
            ['fk_montadora' => '118', 'descricao' => 'PASSAT'],
            ['fk_montadora' => '118', 'descricao' => 'PASSAT VARIANT'],
            ['fk_montadora' => '118', 'descricao' => 'POINTER'],
            ['fk_montadora' => '118', 'descricao' => 'POLO'],
            ['fk_montadora' => '118', 'descricao' => 'POLO SEDAN'],
            ['fk_montadora' => '118', 'descricao' => 'QUANTUM'],
            ['fk_montadora' => '118', 'descricao' => 'SANTANA'],
            ['fk_montadora' => '118', 'descricao' => 'SAVEIRO'],
            ['fk_montadora' => '118', 'descricao' => 'SCIROCCO'],
            ['fk_montadora' => '118', 'descricao' => 'SP2'],
            ['fk_montadora' => '118', 'descricao' => 'SPACE CROSS'],
            ['fk_montadora' => '118', 'descricao' => 'SPACEFOX'],
            ['fk_montadora' => '118', 'descricao' => 'TIGUAN'],
            ['fk_montadora' => '118', 'descricao' => 'TL'],
            ['fk_montadora' => '118', 'descricao' => 'TOUAREG'],
            ['fk_montadora' => '118', 'descricao' => 'UP'],
            ['fk_montadora' => '118', 'descricao' => 'VAN'],
            ['fk_montadora' => '118', 'descricao' => 'VARIANT'],
            ['fk_montadora' => '118', 'descricao' => 'VARIANT II'],
            ['fk_montadora' => '118', 'descricao' => 'VOYAGE'],
            ['fk_montadora' => '119', 'descricao' => '460'],
            ['fk_montadora' => '119', 'descricao' => '850'],
            ['fk_montadora' => '119', 'descricao' => '960'],
            ['fk_montadora' => '119', 'descricao' => 'C30'],
            ['fk_montadora' => '119', 'descricao' => 'S40'],
            ['fk_montadora' => '119', 'descricao' => 'S60'],
            ['fk_montadora' => '119', 'descricao' => 'S80'],
            ['fk_montadora' => '119', 'descricao' => 'V40'],
            ['fk_montadora' => '119', 'descricao' => 'V50'],
            ['fk_montadora' => '119', 'descricao' => 'V60'],
            ['fk_montadora' => '119', 'descricao' => 'V70'],
            ['fk_montadora' => '119', 'descricao' => 'XC60'],
            ['fk_montadora' => '119', 'descricao' => 'XC70'],
            ['fk_montadora' => '119', 'descricao' => 'XC90'],
            ['fk_montadora' => '120', 'descricao' => 'BUGGY'],
            ['fk_montadora' => '121', 'descricao' => '96A'],
            ['fk_montadora' => '122', 'descricao' => 'AERO-WILLYS'],
            ['fk_montadora' => '122', 'descricao' => 'INTERLAGOS'],
            ['fk_montadora' => '122', 'descricao' => 'JEEP'],
            ['fk_montadora' => '122', 'descricao' => 'RURAL'],
            ['fk_montadora' => '123', 'descricao' => 'CJ2A'],
            ['fk_montadora' => '123', 'descricao' => 'JEEP']
        ]);
    }
}
